### ISSUE TITLE
Adding bootstrap classes to form elements

### ISSUE THREAD

**Issue by sgoudie** [meteor-useraccounts/bootstrap#20]
I may have missed something really obvious, but when using the bootstrap package my forms and buttons don't have the classes attached to them. Either I'm missing something, or need to know how to add the classes directly to them.

Thanks guys, this is a really useful package!

**Comment by splendido** [comment]
Hello @sgoudie,
lets consider that there's no `boostrap` styles included with `useraccounts:bootstrap`.
This is to let you choose how to include them. See [here](https://github.com/meteor-useraccounts/bootstrap#bring-your-own-bootstrap)

Lets have a look at the [boilerplates](https://github.com/meteor-useraccounts/boilerplates)!

Let me know if you solve the problem!
