### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/bootstrap#25]
any easyish way to make this work as a modal form?

**Comment by splendido** [comment]
hello @Maxhodges,
I know there was some previous successful attemp to make it with modals.
See [this issue](https://github.com/meteor-useraccounts/core/issues/180) on the core repo.

**Comment by splendido** [comment]
Any progress on this?

**Comment by Maxhodges** [comment]
This package for modals is very simple. We like it a alot:
https://atmospherejs.com/peppelg/bootstrap-3-modal

You only need to add the a "modal" class to a div wrapper in your template.
Might be a good starting point if someone wanted to integrate modals into useraccounts/bootstrap.

**Comment by Maxhodges** [comment]
OK here is how I got modals working in a few easy steps

#### First Add the [peppelg:bootstrap-3-modal package](https://atmospherejs.com/peppelg/bootstrap-3-modal)

#### Next create a template and *add these modal tags*
```
<template name="login">
  <div class="modal fade">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <!--<div class="modal-header">-->
          <!--Sign-in-->
        <!--</div>-->
        <div class="modal-body">
        <div id="login" class="form-signin">
            {{> atForm}}
        </div>
        </div>
      </div>
    </div>
  </div>
</template>
```

#### Next, when you want to show your modal call this command from your event handler 
```
Modal.show('login'); // login being the template name
```

example:
```
Template.header.events({
  'click .__signin': function() {
    console.count('click signin');
    Modal.show('login');
  },
});
```
#### Add this onSubmit hook to your AccountsTemplate config
```
AccountsTemplates.configure({
    onSubmitHook: mySubmitFunc
});
```
### and write callback to close your signin/signup form
```
var mySubmitFunc = function(error, state){
  if (!error) {
    if (state === "signIn") {
      // Successfully logged in
      // ...
      Modal.hide('login');
    }
    if (state === "signUp") {
      // Successfully registered
      // ...
      Modal.hide('login');
    }
  }
};
```

**Comment by splendido** [comment]
great work!

...for the PR, since it's bootstrap specific: what about adding all this as an example [somewhere around on the wiki](https://github.com/meteor-useraccounts/wiki)?
It's still not well organized, but I hope there will be a time where everything there will be put somewhere well organized!

...perhaps a link to this *wiki* on the `Guide.md` wouldn't be bad ;-)

**Comment by Maxhodges** [comment]
since the modal technique above bypasses all the routing, what do you think of creating a separate repo where we rip out all the routing code in order to keep it super  lean?

**Comment by splendido** [comment]
`useraccounts@2.0` is on the works!

...lets wait for it and we'll have a number of plugin packages to get *routing*, *i18n*, *modals*, etc... ;-)

**Comment by splendido** [comment]
See the [modal-forms](https://trello.com/c/uQ0wipnG/14-modal-forms) card on Trello

**Comment by derwaldgeist** [comment]
Just came across this and tried to use @Maxhodges approach. It sort of works, but if the user commits the login dialog, my (flow) router always jumps to the home page of the application. Suprisingly, it does not do this if I am using the standard full-page login approach. So I am wondering why this additional routing takes place?

**Comment by Maxhodges** [comment]
My understanding is that it jumps back to the previous page on login, but
believe you can override this behavior.

*Links*homeRoutePathString'/'Path for the home route, to be possibly used
for redirects after successful form submission.

**Comment by derwaldgeist** [comment]
Thanks for this tip, I have not seen this homeRoutePath. Unfortunately, it can only be set as part of the configuration and not on a per-use base. I will try to set it to "#" to prevent any re-routing.

**Comment by Maxhodges** [comment]
i came up with another method to have a bit more control over the post login routing. will post when I'm back at my desk. now on holiday.

**Comment by splendido** [comment]
Hey guys, lets have a look at [this discussion](https://github.com/meteor-useraccounts/core/issues/180).

My suggestion it to set `AccountsTemplates.avoidRedirect` to `true` before showing the modal.
Lets also have a look at [this thread](https://github.com/meteor-useraccounts/core/issues/153#issuecomment-62595846) and especially at [this comment](https://github.com/meteor-useraccounts/core/issues/153#issuecomment-62595846)

**Comment by splendido** [comment]
...realizing now the above applies to `useraccounts:iron-routing`, but `useraccounts:flow-routing` is currently missing this part.

See [this line](https://github.com/meteor-useraccounts/iron-routing/blob/master/lib/client.js#L135) for `useraccounts:iron-routing`

See [this line](https://github.com/meteor-useraccounts/flow-routing/blob/master/lib/client/client.js#L96) for `useraccounts:flow-routing`

I'll continue this discussion on https://github.com/meteor-useraccounts/flow-routing/issues/12
