### ISSUE TITLE
onError hooks?

### ISSUE THREAD

**Issue by Maxhodges** [meteor-useraccounts/bootstrap#28]
are there any hooks for on signin error so I could animate the form with a shake?

**Comment by Maxhodges** [comment]
basically should just in-line the package into my project so I can override AT error helpers?

**Comment by splendido** [comment]
you can use [onSubmitHook](https://github.com/meteor-useraccounts/core/blob/6fb321c88168887b8d3a38dcd153b3825c207a06/Guide.md#onsubmithook) checking there's actually and error
