### ISSUE TITLE
Template Customization

### ISSUE THREAD

**Issue by neetVeritas** [meteor-useraccounts/bootstrap#31]
This isn't really much of an actual issue, though I've recently stumbled upon this package and I was wondering if there was any way to modify the Sign In / Sign Up templates. For instance, add Bootstrap's inputgroups to generated fields. I tried dabblign with the package, but I'm relatively new to Meteor and I didn't manage to find anything useful within my main meteor directory.

**Comment by splendido** [comment]
please have a look at the issues on the core repo.
There's also a bit about this around. This [search](https://github.com/meteor-useraccounts/core/issues?q=is%3Aissue+aldeed+is%3Aclosed) might be a good start.

Feel free to ask more about this, but please do it on the core repo.
