### ISSUE TITLE
custom templates

### ISSUE THREAD

**Issue by gussandy** [meteor-useraccounts/bootstrap#32]
Hi...I'm implementing a custom template for my app and using aldeed form extension plugin to replace the native atForm template however, does this mean that I would have to implement form validation and everything else {{> atForm}} is suppose to take care of? I've tried using AccountsTemplates.addFields but this doesn't seem to work. Your thoughts would be richly appreciated. Thanks

**Comment by splendido** [comment]
Hello @gussandy,
as long as you leave the required sub-templates in place, everything should work as expected!

Please see [this issue on the core repo](https://github.com/meteor-useraccounts/core/issues/300)
