### ISSUE TITLE
Load different form state in modal based on session

### ISSUE THREAD

**Issue by jasenkoh** [meteor-useraccounts/bootstrap#38]
Hello,

I am trying to load form inside a modal based on session variable, but once the modal is shown with corresponding form I am not able to navigate between each other any more. i.e. when I open signIn state I can't click on Register link inside modal and vice versa.

```html
<template name="login">
  <div class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
        <div id="login" class="form-signin">
            {{> atForm state=state}}
        </div>
        </div>
      </div>
    </div>
  </div>
</template>
```
```coffescript
Template.login.helpers
  state: ->
    return Session.get 'templateState' or 'signUp'
```
```coffescript
Template.navbar.events
  'click .sign-in': (e, t) ->
    Session.set 'templateState', 'signIn'
    Modal.show 'login'
  'click .sign-up': (e, t) ->
    Session.set 'templateState', 'signUp'
    Modal.show 'login'
```
Any suggestions?

**Comment by splendido** [comment]
I'd say the rigth way to do it is by using `AccountsTemplates.setState` inside your event handlers rather than `{{> atForm state=state}}`.

```html
<template name="login">
  <div class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
        <div id="login" class="form-signin">
            {{> atForm}}
        </div>
        </div>
      </div>
    </div>
  </div>
</template>
```


```coffeescript
Template.navbar.events
  'click .sign-in': (e, t) ->
    AccountsTemplates.setState('signIn')
    Modal.show 'login'
  'click .sign-up': (e, t) ->
    AccountsTemplates.setState('signUp')
    Modal.show 'login'
```

The internal state for AT is kept with a reactive var so everytime you change it you get the `atForm` template adapted to the new state.

If you're playing with modals, you might want to have a look at [this discussion](https://github.com/meteor-useraccounts/core/issues/180)

**Comment by jasenkoh** [comment]
@splendido `AccountsTemplates.setState` works like charm, thank you.

Ciao
