### ISSUE TITLE
make accounts-templates-bootstrap.less optional

### ISSUE THREAD

**Issue by djhi** [meteor-useraccounts/bootstrap#4]
It would be nice to have the choice to include it. It doesn't play well with some bootswatch themes (slate for one).

Renaming it to accounts-templates-bootstrap.import.less would do the trick :)

**Comment by Maxhodges** [comment]
maybe I'm just not good at css, but is there anyway to change the button color? my signin button has classes `at-btn btn btn-default` I'd prefer to remove btn-default and add btn-success. I tried to do it in the signin templates onRendered with this jquery, but it's not working `$('.at-btn').removeClass('btn-default').addClass('btn-success');` perhaps because of the dynamic nature of the template. Are there any hidden events I can hook into like when it switches between signin and signup?

**Comment by Maxhodges** [comment]
I've also tried to override the style with a more specific selector, but nothing works

```
button #at-btn {
  background-color: red;
}


button .at-btn .btn {
  background-color: blue;
}
```

**Comment by Maxhodges** [comment]
ah Ok finally got it with this 

```
#at-btn {
  background-color: #5ebd5e;
  border-color: #5ebd5e;
  color: #FFFFFF
}

#at-btn:hover, #at-btn:focus, #at-btn:active, #at-btn.active, .open .dropdown-toggle#at-btn {
  background-color: #74d348;
  border-color: #74d348;
  color: #FFFFFF
}

#at-btn:active, #at-btn.active, .open .dropdown-toggle#at-btn {
  background-image: none
}

#at-btn.disabled, #at-btn.disabled:hover, #at-btn.disabled:focus, #at-btn.disabled:active, #at-btn.disabled.active, #at-btn[disabled], #at-btn[disabled]:hover, #at-btn[disabled]:focus, #at-btn[disabled]:active, #at-btn.active[disabled], fieldset[disabled] #at-btn, fieldset[disabled] #at-btn:hover, fieldset[disabled] #at-btn:focus, fieldset[disabled] #at-btn:active, fieldset[disabled] #at-btn.active {
  background-color: #56b22b;
  border-color: #56b22b
}

```

**Comment by splendido** [comment]
I'd say the best option is to replace the [atPwdFormBtn](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_pwd_form_btn.html) template with this:

```html
<template name="myAtPwdFormBtn">
  <button type="submit" class="at-btn submit btn btn-lg btn-block btn-success {{submitDisabled}}" id="at-btn">
    {{buttonText}}
  </button>
</template>
```

```javascript
Template.myAtPwdFormBtn.replaces("atPwdFormBtn");
```

having [aldeed:template-extension](https://atmospherejs.com/aldeed/template-extension) package installed

**Comment by Maxhodges** [comment]
OK yeah I used that library once before. Sounds like a good idea. Thanks!
